sudo: false

language: java

jdk:
    - oraclejdk8

services:
    - docker

notifications:
    email:
        - builds@fitbur.com
    on-success: change
    on-failure: always

cache:
    apt: true
    pip: true
    directories:
        - $HOME/.m2

addons:
    apt:
        packages:
            - gnupg
            - net-tools
            
env:
  global:
    - DOCKER_TLS_VERIFY=""
    - DOCKER_HOST="http://127.0.0.1:2375"
    - DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"

before_install:
    - ./before_install.sh

script: ./script.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - ./after_success.sh
    
